const { getSubtitles } = require('youtube-captions-scraper');

module.exports = async (req, res) => {
    // Enable CORS
    res.setHeader('Access-Control-Allow-Origin', '*');
    res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
    res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

    // Handle preflight request
    if (req.method === 'OPTIONS') {
        return res.status(200).end();
    }

    // Only allow GET requests
    if (req.method !== 'GET') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    const { videoId } = req.query;
    const lang = req.query.lang || 'en';
    const allowAuto = req.query.auto === 'true';
    const includeTimestamps = req.query.timestamps === 'true';
    
    console.log(`Fetching captions for video ID: ${videoId}`);
    console.log(`Language: ${lang}, Allow Auto-generated: ${allowAuto}`);

    try {
        // Try to get manual captions first
        try {
            const captions = await getSubtitles({
                videoID: videoId,
                lang: lang
            });

            if (captions && captions.length > 0) {
                const fullText = captions
                    .map(caption => {
                        if (includeTimestamps) {
                            const startTime = Math.floor(caption.start);
                            const hours = Math.floor(startTime / 3600);
                            const minutes = Math.floor((startTime % 3600) / 60);
                            const seconds = startTime % 60;
                            const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                            return `${timestamp} ${caption.text}`;
                        }
                        return caption.text;
                    })
                    .join('\n')
                    .trim();

                console.log(`Successfully fetched manual captions. Length: ${fullText.length} characters`);
                return res.status(200).send(fullText);
            }
        } catch (error) {
            console.log('Manual captions not found:', error.message);
        }

        // If manual captions aren't available and auto-generated are allowed, try those
        if (allowAuto) {
            try {
                console.log('Attempting to fetch auto-generated captions...');
                const autoCaptions = await getSubtitles({
                    videoID: videoId,
                    lang: lang,
                    auto: true
                });

                if (autoCaptions && autoCaptions.length > 0) {
                    const fullText = autoCaptions
                        .map(caption => {
                            if (includeTimestamps) {
                                const startTime = Math.floor(caption.start);
                                const hours = Math.floor(startTime / 3600);
                                const minutes = Math.floor((startTime % 3600) / 60);
                                const seconds = startTime % 60;
                                const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                                return `${timestamp} ${caption.text}`;
                            }
                            return caption.text;
                        })
                        .join('\n')
                        .trim();

                    console.log(`Successfully fetched auto-generated captions. Length: ${fullText.length} characters`);
                    return res.status(200).send(fullText);
                }
            } catch (error) {
                console.log('Auto-generated captions not found:', error.message);
            }
        }

        // If we get here, no captions were found
        throw new Error(`No ${allowAuto ? 'manual or auto-generated' : 'manual'} captions found for language: ${lang}`);

    } catch (error) {
        console.error('Error processing request:', error);
        
        return res.status(404).json({
            error: 'Captions not found',
            videoId,
            language: lang,
            autoGenerated: allowAuto,
            details: error.message,
            timestamp: new Date().toISOString()
        });
    }
};
