const express = require('express');
const router = express.Router();
const { getSubtitles } = require('youtube-captions-scraper');

// Legacy endpoint for v3 compatibility
router.get('/:videoId', async (req, res) => {
    const videoId = req.params.videoId;
    const lang = req.query.lang || 'en';
    const allowAuto = req.query.auto === 'true';
    const includeTimestamps = req.query.timestamps === 'true';
    
    console.log(`${new Date().toISOString()} - Fetching captions for video ID: ${videoId}`);
    console.log(`Language: ${lang}, Allow Auto-generated: ${allowAuto}`);

    try {
        // Try to get manual captions first
        try {
            const captions = await getSubtitles({
                videoID: videoId,
                lang: lang
            });

            if (captions && captions.length > 0) {
                const fullText = captions
                    .map(caption => {
                        if (includeTimestamps) {
                            const startTime = Math.floor(caption.start);
                            const hours = Math.floor(startTime / 3600);
                            const minutes = Math.floor((startTime % 3600) / 60);
                            const seconds = startTime % 60;
                            const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                            return `${timestamp} ${caption.text}`;
                        }
                        return caption.text;
                    })
                    .join('\n')
                    .trim();

                console.log(`Successfully fetched manual captions. Length: ${fullText.length} characters`);
                return res.send(fullText);
            }
        } catch (error) {
            console.log('Manual captions not found:', error.message);
        }

        // If manual captions aren't available and auto-generated are allowed, try those
        if (allowAuto) {
            try {
                console.log('Attempting to fetch auto-generated captions...');
                const autoCaptions = await getSubtitles({
                    videoID: videoId,
                    lang: lang,
                    auto: true
                });

                if (autoCaptions && autoCaptions.length > 0) {
                    const fullText = autoCaptions
                        .map(caption => {
                            if (includeTimestamps) {
                                const startTime = Math.floor(caption.start);
                                const hours = Math.floor(startTime / 3600);
                                const minutes = Math.floor((startTime % 3600) / 60);
                                const seconds = startTime % 60;
                                const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                                return `${timestamp} ${caption.text}`;
                            }
                            return caption.text;
                        })
                        .join('\n')
                        .trim();

                    console.log(`Successfully fetched auto-generated captions. Length: ${fullText.length} characters`);
                    return res.send(fullText);
                }
            } catch (error) {
                console.log('Auto-generated captions not found:', error.message);
            }
        }

        // If we get here, no captions were found
        throw new Error(`This video does not have any ${allowAuto ? '' : 'manual '}captions available. Please try a different video.`);

    } catch (error) {
        console.error('Error processing request:', error);
        
        res.status(404).json({
            error: 'Captions not found',
            videoId,
            language: lang,
            autoGenerated: allowAuto,
            details: error.message,
            timestamp: new Date().toISOString()
        });
    }
});

// New endpoint for v4
router.get('/fetch', async (req, res) => {
    try {
        const { url, auto = 'true' } = req.query;
        if (!url) {
            return res.status(400).json({ error: 'URL parameter is required' });
        }

        // Extract video ID from URL
        const match = url.match(/(?:youtube\.com\/(?:[^\/]+\/.+\/|(?:v|e(?:mbed)?)\/|.*[?&]v=)|youtu\.be\/)([^"&?\/\s]{11})/);
        if (!match) {
            return res.status(400).json({ error: 'Invalid YouTube URL' });
        }

        const videoId = match[1];
        const lang = 'en';
        const allowAuto = auto === 'true';
        const includeTimestamps = true;

        console.log(`${new Date().toISOString()} - Fetching captions for video ID: ${videoId}`);
        console.log(`Language: ${lang}, Allow Auto-generated: ${allowAuto}`);

        // Try to get manual captions first
        try {
            const captions = await getSubtitles({
                videoID: videoId,
                lang: lang
            });

            if (captions && captions.length > 0) {
                const fullText = captions
                    .map(caption => {
                        const startTime = Math.floor(caption.start);
                        const hours = Math.floor(startTime / 3600);
                        const minutes = Math.floor((startTime % 3600) / 60);
                        const seconds = startTime % 60;
                        const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                        return `${timestamp} ${caption.text}`;
                    })
                    .join('\n')
                    .trim();

                console.log(`Successfully fetched manual captions. Length: ${fullText.length} characters`);
                return res.json({
                    captions: {
                        playerCaptionsTracklistRenderer: {
                            captionTracks: [{
                                languageCode: lang,
                                name: { simpleText: 'English' },
                                baseUrl: fullText
                            }]
                        }
                    }
                });
            }
        } catch (error) {
            console.log('Manual captions not found:', error.message);
        }

        // If manual captions aren't available and auto-generated are allowed, try those
        if (allowAuto) {
            try {
                console.log('Attempting to fetch auto-generated captions...');
                const autoCaptions = await getSubtitles({
                    videoID: videoId,
                    lang: lang,
                    auto: true
                });

                if (autoCaptions && autoCaptions.length > 0) {
                    const fullText = autoCaptions
                        .map(caption => {
                            const startTime = Math.floor(caption.start);
                            const hours = Math.floor(startTime / 3600);
                            const minutes = Math.floor((startTime % 3600) / 60);
                            const seconds = startTime % 60;
                            const timestamp = `[${hours.toString().padStart(2, '0')}:${minutes.toString().padStart(2, '0')}:${seconds.toString().padStart(2, '0')}]`;
                            return `${timestamp} ${caption.text}`;
                        })
                        .join('\n')
                        .trim();

                    console.log(`Successfully fetched auto-generated captions. Length: ${fullText.length} characters`);
                    return res.json({
                        captions: {
                            playerCaptionsTracklistRenderer: {
                                captionTracks: [{
                                    languageCode: lang,
                                    name: { simpleText: 'English (auto-generated)' },
                                    baseUrl: fullText
                                }]
                            }
                        }
                    });
                }
            } catch (error) {
                console.log('Auto-generated captions not found:', error.message);
            }
        }

        // If we get here, no captions were found
        throw new Error(`This video does not have any ${allowAuto ? '' : 'manual '}captions available. Please try a different video.`);

    } catch (error) {
        console.error('Error fetching captions:', error);
        res.status(404).json({ 
            error: 'Captions not found',
            details: error.message,
            timestamp: new Date().toISOString()
        });
    }
});

module.exports = router;
